### ISSUE TITLE
lab-configuring-apps-with-configmaps

### ISSUE THREAD

**Issue by joker-bai** [labex-labs/scenarios#363]
> **Please read [For Newbie](https://github.com/labex-labs/scenarios/issues/18) first. 请先阅读 [新手须知](https://github.com/labex-labs/scenarios/issues/18)。**

## Basic

> Basic information about the scenario, which can be changed if required.
> 实验/挑战的基本信息，如有需要，可以修改。

- **Suggest Title 建议标题**:  Configuring Apps with ConfigMaps
- **Suggest Steps 建议步骤数**: 5
- **Suggest Image 建议环境**: `vnc-instance-ubuntu:2204`

## Sources

> Issues has provided the material; the part not provided must be completed by the author.
> Issues 已经提供了材料；没有提供的部分由作者自行补充完成。

- [x] Full Text 正文内容
- [ ] Verify Script 检测脚本

## Skills

> Suggested skills to include can be modified as needed. **The main skill points that should be included in this section are bolded**. From [Skills Tree](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp).
> 建议包括的 Skills ID，可以根据需要增删。**本章节应包含的主要技能点已加粗**，技能点来自 [技能树](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp)

- **`kubernetes/apply`**
- `kubernetes/exec`
- `kubernetes/get`
- `kubernetes/rollout`

**Comment by joker-bai** [comment]
# Configuring Apps with ConfigMaps

## Introduction

In this lab, you will learn how to use ConfigMaps in Kubernetes to configure your applications. ConfigMaps provide a way to separate configuration data from your application code, making it easy to manage and update your application configuration without modifying the application itself.


## Step 1: Create a ConfigMap

In this step, you will create a ConfigMap containing the configuration data for your application.

Create a file named `configmap.yaml` with the following contents:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
data:
  DATABASE_URL: postgres://user:password@host:port/dbname
```

This ConfigMap contains a single key-value pair, where the key is `DATABASE_URL` and the value is a PostgreSQL database connection string.

To create the ConfigMap, run the following command:

```bash
kubectl apply -f configmap.yaml
```

## Step 2: Use the ConfigMap in Your Application

In this step, you will use the ConfigMap in your application.

Create a file named `deployment.yaml` with the following contents:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: nginx:latest
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: DATABASE_URL
```

This deployment specifies a single container running your application, which uses the `DATABASE_URL` environment variable to connect to a PostgreSQL database. The value of `DATABASE_URL` is obtained from the `my-config` ConfigMap.

To create the deployment, run the following command:

```bash
kubectl apply -f deployment.yaml
```

## Step 3: Verify the Configuration

In this step, you will verify that the configuration has been applied to your application.

First, find the name of the pod running your application by running the following command:

```bash
kubectl get pods -l app=my-app
```

You should see a single pod running your application. Note the name of the pod.

Next, run the following command to open a shell session in the container running your application:

```bash
kubectl exec -it <pod-name> -- sh
```

Replace `<pod-name>` with the name of the pod that you noted earlier.

Once you are in the shell session, run the following command to print the value of the `DATABASE_URL` environment variable:

```bash
echo $DATABASE_URL
```

You should see the database connection string that you set in the ConfigMap.

## Step 4: Update the ConfigMap

In this step, you will update the ConfigMap and see how it affects your application.

Update the `configmap.yaml` file with a new value for the `DATABASE_URL` key:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
data:
  DATABASE_URL: postgres://newuser:newpassword@newhost:newport/newdbname
```

This updates the `DATABASE_URL` key to a new value.

To update the ConfigMap, run the following command:

```bash
kubectl apply -f configmap.yaml
```

## Step 5: Verify the Update

In this step, you will verify that the update to the ConfigMap has been applied to your application.

First, find the name of the pod running your application by running the following command:

```bash
kubectl get pods -l app=my-app
```

You should see a single pod running your application. Note the name of the pod.

Next, run the following command to open a shell session in the container running your application:

```bash
kubectl exec -it <pod-name> -- sh
```

Replace `<pod-name>` with the name of the pod that you noted earlier.

Once you are in the shell session, run the following command to print the value of the `DATABASE_URL` environment variable:

```bash
echo $DATABASE_URL
```

You can see that the configuration did not take effect, it is still the same data as before. You need to restart Deployment with the following command.

```bash
kubectl rollout restart deployment my-app
```

When the reboot is complete, go inside the container again and use the above command to check the configuration.

You should see the updated database connection string.


## Summary

In this lab, you learned how to use ConfigMaps in Kubernetes to configure your applications. You created a ConfigMap containing configuration data, used the ConfigMap in your application, and updated the ConfigMap to see how it affects your application. You also learned how to verify that the configuration was applied to your application and how to clean up the resources created in the lab.
