### ISSUE TITLE
lab-storing-application-data-with-persistentvolumes

### ISSUE THREAD

**Issue by joker-bai** [labex-labs/scenarios#365]
> **Please read [For Newbie](https://github.com/labex-labs/scenarios/issues/18) first. 请先阅读 [新手须知](https://github.com/labex-labs/scenarios/issues/18)。**

## Basic

> Basic information about the scenario, which can be changed if required.
> 实验/挑战的基本信息，如有需要，可以修改。

- **Suggest Title 建议标题**:  Storing Application Data with PersistentVolumes
- **Suggest Steps 建议步骤数**: 5
- **Suggest Image 建议环境**: `vnc-instance-ubuntu:2204`

## Sources

> Issues has provided the material; the part not provided must be completed by the author.
> Issues 已经提供了材料；没有提供的部分由作者自行补充完成。

- [x] Full Text 正文内容
- [ ] Verify Script 检测脚本

## Skills

> Suggested skills to include can be modified as needed. **The main skill points that should be included in this section are bolded**. From [Skills Tree](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp).
> 建议包括的 Skills ID，可以根据需要增删。**本章节应包含的主要技能点已加粗**，技能点来自 [技能树](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp)

- **`kubernetes/apply`**
- `kubernetes/get`
- `kubernetes/exec`

**Comment by joker-bai** [comment]
# Storing Application Data with PersistentVolumes

In this lab, you will learn how to store application data with PersistentVolumes in Kubernetes. 

## Introduction

PersistentVolumes (PVs) are Kubernetes resources that represent a piece of networked storage in a cluster. They can be used to store application data in a way that is independent of the container lifecycle. This means that data can be preserved even if the container is terminated or moved to another node.

In this lab, you will create a PersistentVolume and use it to store data from a simple web application. You will then modify the application to use a PersistentVolumeClaim (PVC) to access the PersistentVolume. Finally, you will modify the PVC to request specific storage resources.

## Prerequisites

Before beginning this lab, you should have a basic understanding of Kubernetes and how to create and deploy applications using Kubernetes manifests. You should also have a Kubernetes cluster set up and configured to use PersistentVolumes.

## Step 1: Create a PersistentVolume

In this step, you will create a PersistentVolume that can be used to store data. You will create a YAML file called `pv.yaml` with the following content:

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data
```

This file creates a PersistentVolume with a capacity of 1Gi and an access mode of ReadWriteOnce. The `hostPath` field specifies that the data will be stored on the host machine at the path `/mnt/data`. The `persistentVolumeReclaimPolicy` field is set to Retain, which means that the data will be preserved even if the PersistentVolume is deleted.

Apply the PersistentVolume to your cluster with the following command:

```shell
kubectl apply -f pv.yaml
```

## Step 2: Deploy a Simple Web Application

In this step, you will deploy a simple web application that will store data on the PersistentVolume you created in Step 1. You will create a YAML file called `web-app.yaml` with the following content:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web-app
          image: nginx
          volumeMounts:
            - name: data
              mountPath: /usr/share/nginx/html/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: my-pvc
```

This file creates a Deployment with one replica and a container that runs the nginx image. The `volumeMounts` field specifies that the container should mount the PersistentVolume at the path `/usr/share/nginx/html/data`. The `volumes` field specifies that the container should use a PersistentVolumeClaim called `my-pvc`.

Apply the Deployment to your cluster with the following command:

```shell
kubectl apply -f web-app.yaml
```

## Step 3: Create a PersistentVolumeClaim

In this step, you will create a PersistentVolumeClaim that will be used to request storage from the PersistentVolume you created in Step 1. You will create a YAML file called `pvc.yaml` with the following content:

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
```

This file creates a PersistentVolumeClaim with an access mode of ReadWriteOnce and a request for 1Gi of storage from the PersistentVolume.

Apply the PersistentVolumeClaim to your cluster with the following command:

```shell
kubectl apply -f pvc.yaml
```

## Step 4: Verify Data Persistence

In this step, you will verify that the data is being persisted on the PersistentVolume. You will access the web application running on the container and write some data to the PersistentVolume.

First, find the name of the pod running your application by running the following command:

```shell
kubectl get pods -l app=web-app
```

You should see a single pod running your application. Note the name of the pod.

Next, run the following command to open a shell session in the container running your application:

```shell
kubectl exec -it <pod-name> -- sh
```

Replace <pod-name> with the name of the pod that you noted earlier.

Once you are in the shell session, run the following command to add a test.txt file:

```shell
echo "This is a test file." > /usr/share/nginx/html/data/test.txt
```

This command creates a file called `test.txt` with the text "This is a test file." in the data directory of the PersistentVolume.

Delete the web application with the following command:

```shell
kubectl delete deployment web-app
```

Recreate the web application with the following command:

```shell
kubectl apply -f web-app.yaml
```

Verify that the file you created in the data directory still exists with the following command:

```shell
kubectl exec <pod-name> -- cat /usr/share/nginx/html/data/test.txt
```

Replace <pod-name> with the name of the pod that you noted earlier.

## Step 5: Modify the PVC Storage Resources

In this step, you will modify the PVC to request specific storage resources from the PersistentVolume. You will modify the `pvc.yaml` file to request 2Gi of storage instead of 1Gi.

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
```

Apply the updated PersistentVolumeClaim to your cluster with the following command:

```shell
kubectl apply -f pvc.yaml
```

## Summary

In this lab, you learned how to store application data with PersistentVolumes in Kubernetes. You created a PersistentVolume, deployed a simple web application that used the PersistentVolume, created a PersistentVolumeClaim to request storage from the PersistentVolume, and modified the PersistentVolumeClaim to request specific storage resources. You also verified that the data was being persisted on the PersistentVolume even if the container was terminated or moved to another node.
