### ISSUE TITLE
lab-isolating-workloads-with-namespaces

### ISSUE THREAD

**Issue by joker-bai** [labex-labs/scenarios#397]
> **Please read [For Newbie](https://github.com/labex-labs/scenarios/issues/18) first. 请先阅读 [新手须知](https://github.com/labex-labs/scenarios/issues/18)。**

## Basic

> Basic information about the scenario, which can be changed if required.
> 实验/挑战的基本信息，如有需要，可以修改。

- **Suggest Title 建议标题**:  Isolating Workloads With Namespaces
- **Suggest Steps 建议步骤数**: 5
- **Suggest Image 建议环境**: `vnc-instance-ubuntu:2204`

## Sources

> Issues has provided the material; the part not provided must be completed by the author.
> Issues 已经提供了材料；没有提供的部分由作者自行补充完成。

- [x] Full Text 正文内容
- [ ] Verify Script 检测脚本

## Skills

> Suggested skills to include can be modified as needed. **The main skill points that should be included in this section are bolded**. From [Skills Tree](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp).
> 建议包括的 Skills ID，可以根据需要增删。**本章节应包含的主要技能点已加粗**，技能点来自 [技能树](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp)

- **`kubernetes/apply`**
- `kubernetes/get`
- `kubernetes/exec`

**Comment by joker-bai** [comment]
# Isolating Workloads With Namespaces

## Introduction

Kubernetes provides namespaces as a way to isolate workloads and resources in a cluster. In this lab, you will learn how to use namespaces to isolate workloads and resources. You will create a namespace, deploy a simple web application in the namespace, and verify that the web application is isolated from the other resources in the cluster.

## Step 1: Create a Namespace

In this step, you will create a namespace called `webapp` to isolate the web application from the other resources in the cluster.

Create a file called `namespace.yaml` with the following contents:

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: webapp
```

Apply the namespace to your cluster with the following command:

```shell
kubectl apply -f namespace.yaml
```

Verify that the namespace was created with the following command:

```shell
kubectl get namespaces
```

You should see the `webapp` namespace in the list of namespaces.

## Step 2: Deploy a Web Application

In this step, you will deploy a simple web application in the `webapp` namespace.

Create a file called `web-app.yaml` with the following contents:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
```

This file creates a Deployment with one replica of a container that runs the latest version of the Nginx web server.

Apply the Deployment to your cluster with the following command:

```shell
kubectl apply -f web-app.yaml
```

Verify that the web application is running in the `webapp` namespace with the following command:

```shell
kubectl get pods -n webapp
```

You should see the `web-app` pod in the list of pods running in the `webapp` namespace.

## Step 3: Expose the Web Application

In this step, you will expose the web application to the outside world using a Kubernetes Service.

Create a file called `web-app-service.yaml` with the following contents:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: web-app
  namespace: webapp
spec:
  selector:
    app: web-app
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
```

This file creates a Service that exposes the web application to the cluster using a ClusterIP.

Apply the Service to your cluster with the following command:

```shell
kubectl apply -f web-app-service.yaml
```

Verify that the Service is running in the `webapp` namespace with the following command:

```shell
kubectl get services -n webapp
```

You should see the `web-app` service in the list of services running in the `webapp` namespace.

## Step 4: Verify Namespace Isolation

In this step, you will verify that the web application is isolated from the other resources in the cluster.

Create a file called `other-app.yaml` with the following contents:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: other
spec:
  replicas: 1
  selector:
    matchLabels:
      app: other
  template:
    metadata:
      labels:
        app: other
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
```
In this file, you are creating another Deployment called `other` in the default namespace that runs a container with the `nginx` image.

Apply the Deployment to your cluster with the following command:

```shell
kubectl apply -f other-app.yaml
```

Verify that the Deployment is running in the default namespace with the following command:

```shell
kubectl get pods
```

You should see the `other` pod in the list of pods running in the default namespace.

## Step5: Verifying Cross-Namaspace Access

First, find the name of the pod running your application by running the following command:

```shell
kubectl get pods -l app=other
```

You should see the `other` pod. Note the name of the pod.

Next, run the following command to open a shell session in the container running your application:

```shell
kubectl exec -it <pod-name> -- sh
```

Replace <pod-name> with the name of the pod that you noted earlier.

Once you are in the shell session, run the following command to access the `web-app` Deployment:

```shell
curl web-app.webapp
```

You should see the HTML response from the Nginx web server.

## Summary

In this lab, you learned how to use namespaces to isolate workloads and resources in a Kubernetes cluster. You created a namespace, deployed a simple web application in the namespace, exposed the web application to the outside world using a Kubernetes Service, and verified that the web application is isolated from the other resources in the cluster.
