### ISSUE TITLE
lab-role-based-access-control-on-kubernetes

### ISSUE THREAD

**Issue by joker-bai** [labex-labs/scenarios#398]
> **Please read [For Newbie](https://github.com/labex-labs/scenarios/issues/18) first. 请先阅读 [新手须知](https://github.com/labex-labs/scenarios/issues/18)。**

## Basic

> Basic information about the scenario, which can be changed if required.
> 实验/挑战的基本信息，如有需要，可以修改。

- **Suggest Title 建议标题**: Role-Based Access Control On Kubernetes
- **Suggest Steps 建议步骤数**: 7
- **Suggest Image 建议环境**: `vnc-instance-ubuntu:2204`

## Sources

> Issues has provided the material; the part not provided must be completed by the author.
> Issues 已经提供了材料；没有提供的部分由作者自行补充完成。

- [x] Full Text 正文内容
- [ ] Verify Script 检测脚本

## Skills

> Suggested skills to include can be modified as needed. **The main skill points that should be included in this section are bolded**. From [Skills Tree](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp).
> 建议包括的 Skills ID，可以根据需要增删。**本章节应包含的主要技能点已加粗**，技能点来自 [技能树](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp)

- **`kubernetes/apply`**
- `kubernetes/get`
- `kubernetes/create`

**Comment by joker-bai** [comment]
# Role-Based Access Control On Kubernetes

## Introduction

In a Kubernetes cluster, Role-Based Access Control (RBAC) is used to control access to resources and operations within the cluster. RBAC allows cluster administrators to define roles and permissions for users, groups, and service accounts to control access to resources and operations within the cluster. In this lab, you will learn how to use RBAC to control access to resources in a Kubernetes cluster.

## Step 1: Create a Namespace

Create a new namespace called `myapp` using the following command:

```shell
kubectl create namespace myapp
```

## Step 2: Create a Role

Create a new Role called `myapp-reader` in the `myapp` namespace that allows users to read pods and services in the namespace using the following YAML file:

```yaml
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: myapp
  name: myapp-reader
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "watch", "list"]
```

This Role allows users to read (get, watch, and list) pods and services in the `myapp` namespace.

Create the Role using the following command:

```shell
kubectl apply -f myapp-reader-role.yaml
```

## Step 3: Create a Role Binding

Create a Role Binding that binds the `myapp-reader` Role to a user or group in the `myapp` namespace. For example, to bind the `myapp-reader` Role to the `developer` user in the `myapp` namespace, create the following YAML file:

```yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: myapp-reader-binding
  namespace: myapp
subjects:
- kind: User
  name: developer
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: myapp-reader
  apiGroup: rbac.authorization.k8s.io
```

This Role Binding binds the `myapp-reader` Role to the `developer` user in the `myapp` namespace.

Create the Role Binding using the following command:

```shell
kubectl apply -f myapp-reader-binding.yaml
```

## Step 4: Test Access

Test access to the `myapp` namespace by attempting to get the list of pods in the namespace using the following command:

```shell
kubectl get pods -n myapp --as developer
```

You should see a list of pods in the `myapp` namespace.

Test access to the `default` namespace by attempting to get the list of pods in the namespace using the following command:

```shell
kubectl get pods --as developer
```

You should see an error message indicating that you do not have access to the `default` namespace.

## Step 5: Create a ClusterRole

Create a new ClusterRole called `myapp-admin` that allows users to create, delete, and update pods and services in all namespaces using the following YAML file:

```yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: myapp-admin
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
```

This ClusterRole allows users to perform all operations (get, list, watch, create, update, and delete) on pods and services in all namespaces.

Create the ClusterRole using the following command:

```shell
kubectl apply -f myapp-admin-clusterrole.yaml
```

## Step 6: Create a ClusterRole Binding

Create a ClusterRole Binding that binds the `myapp-admin` ClusterRole to a user or group in the cluster. For example, to bind the `myapp-admin` ClusterRole to the `cluster-admin` user, create the following YAML file:

```yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: myapp-admin-binding
subjects:
- kind: User
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: myapp-admin
  apiGroup: rbac.authorization.k8s.io
```

This ClusterRole Binding binds the `myapp-admin` ClusterRole to the `cluster-admin` user.

Create the ClusterRole Binding using the following command:

```shell
kubectl apply -f myapp-admin-binding.yaml
```

## Step 7: Test Access

Test access to create a pod in the `myapp` namespace by creating a pod using the following YAML file:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  namespace: myapp
spec:
  containers:
  - name: myapp-container
    image: nginx
    ports:
    - containerPort: 80
```

Create the pod using the following command:

```shell
kubectl apply -f myapp-pod.yaml --as cluster-admin
```

You should see a message indicating that the pod was created.

Test access to create a deployment in the `myapp` namespace by creating a deployment using the following YAML file:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  namespace: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-deployment
  template:
    metadata:
      labels:
        app: myapp-deployment
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
```

Create the pod using the following command:

```shell
kubectl apply -f myapp-deployment.yaml --as cluster-admin
```

You should see an error message indicating that you do not have access to create deploymeny in the `myapp` namespace.

## Summary

In this lab, you learned how to use Role-Based Access Control (RBAC) in Kubernetes to control access to resources and operations within the cluster. You created a namespace, a Role, and a Role Binding to control access to resources in a specific namespace. You also created a ClusterRole and a ClusterRole Binding to control access to resources across all namespaces. By the end of this lab, you should have a good understanding of how to use RBAC to control access to resources and operations in a Kubernetes cluster.
