### ISSUE TITLE
lab-running-pod-with-daemonsets

### ISSUE THREAD

**Issue by joker-bai** [labex-labs/scenarios#399]
> **Please read [For Newbie](https://github.com/labex-labs/scenarios/issues/18) first. 请先阅读 [新手须知](https://github.com/labex-labs/scenarios/issues/18)。**

## Basic

> Basic information about the scenario, which can be changed if required.
> 实验/挑战的基本信息，如有需要，可以修改。

- **Suggest Title 建议标题**: Running Pod With DaemonSets
- **Suggest Steps 建议步骤数**: 5
- **Suggest Image 建议环境**: `vnc-instance-ubuntu:2204`

## Sources

> Issues has provided the material; the part not provided must be completed by the author.
> Issues 已经提供了材料；没有提供的部分由作者自行补充完成。

- [x] Full Text 正文内容
- [ ] Verify Script 检测脚本

## Skills

> Suggested skills to include can be modified as needed. **The main skill points that should be included in this section are bolded**. From [Skills Tree](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp).
> 建议包括的 Skills ID，可以根据需要增删。**本章节应包含的主要技能点已加粗**，技能点来自 [技能树](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp)

- **`kubernetes/apply`**
- `kubernetes/get`

**Comment by joker-bai** [comment]
# Running Pod With DaemonSets

## Introduction

In Kubernetes, a DaemonSet is a type of controller that ensures a copy of a pod is running on every node in the cluster. This lab will guide you through the process of creating a DaemonSet to run replicas of a pod on every node in the cluster.

## Step 1: Create a Pod

Create a simple pod that will be used as the template for the replicas. Create a file called `myapp-pod.yaml` with the following contents:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
spec:
  containers:
  - name: myapp-container
    image: nginx
    ports:
    - containerPort: 80
```

Create the pod using the following command:

```shell
kubectl apply -f myapp-pod.yaml
```

## Step 2: Create a DaemonSet

Create a DaemonSet to run replicas of the `myapp-pod` on every node in the cluster. Create a file called `myapp-daemonset.yaml` with the following contents:

```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: myapp-daemonset
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-container
        image: nginx
        ports:
        - containerPort: 80
```

This DaemonSet uses the `myapp-pod` as the template for the replicas and sets the `matchLabels` selector to `app: myapp` to ensure that the replicas are created on every node.

Create the DaemonSet using the following command:

```shell
kubectl apply -f myapp-daemonset.yaml
```

## Step 3: Verify the DaemonSet

Verify that the DaemonSet has been created and that replicas of the `myapp-pod` are running on every node. Use the following command to list the nodes in the cluster:

```shell
kubectl get nodes
```

Use the following command to list the pods created by the DaemonSet:

```shell
kubectl get pods -l app=myapp
```

You should see one pod for each node in the cluster.

## Step 4: Update the DaemonSet

Update the DaemonSet to change the image used by the `myapp-container`. Create a file called `myapp-daemonset-update.yaml` with the following contents:

```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: myapp-daemonset
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-container
        image: busybox
        command: ['sleep', '3600']
```

This updated DaemonSet changes the image used by the `myapp-container` to `busybox` and sets the command to `sleep 3600`.

Update the DaemonSet using the following command:

```shell
kubectl apply -f myapp-daemonset-update.yaml
```

## Step 5: Verify the Update

Verify that the DaemonSet has been updated and that replicas of the `myapp-pod` are running with the new image. Use the following command to list the pods created by the DaemonSet:

```shell
kubectl get pods -l app=myapp
```

You should see new pods created with the updated image.

## Summary

In this lab, you learned how to use a DaemonSet in Kubernetes to run replicas of a pod on every node in the cluster.
