### ISSUE TITLE
lab-networking-with-ingress-on-kubernetes

### ISSUE THREAD

**Issue by joker-bai** [labex-labs/scenarios#402]
> **Please read [For Newbie](https://github.com/labex-labs/scenarios/issues/18) first. 请先阅读 [新手须知](https://github.com/labex-labs/scenarios/issues/18)。**

## Basic

> Basic information about the scenario, which can be changed if required.
> 实验/挑战的基本信息，如有需要，可以修改。

- **Suggest Title 建议标题**: Networking With Ingress On Kubernetes
- **Suggest Steps 建议步骤数**: 4
- **Suggest Image 建议环境**: `vnc-instance-ubuntu:2204`

## Sources

> Issues has provided the material; the part not provided must be completed by the author.
> Issues 已经提供了材料；没有提供的部分由作者自行补充完成。

- [x] Full Text 正文内容
- [ ] Verify Script 检测脚本

## Skills

> Suggested skills to include can be modified as needed. **The main skill points that should be included in this section are bolded**. From [Skills Tree](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp).
> 建议包括的 Skills ID，可以根据需要增删。**本章节应包含的主要技能点已加粗**，技能点来自 [技能树](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp)

- **`kubernetes/apply`**
- `kubernetes/create`
- `kubernetes/get`

**Comment by joker-bai** [comment]
# Networking With Ingress On Kubernetes

In this lab, you will learn how to use Ingress to route external traffic to services running in a Kubernetes cluster. 

## Introduction

Kubernetes Ingress is a powerful tool for managing external access to services in a Kubernetes cluster. Ingress acts as a layer 7 load balancer, allowing you to route traffic to different services based on the incoming URL path or hostname. 

In this lab, we will create a sample application and expose it to the outside world using Ingress. We will use `nginx-ingress` as the Ingress controller, which is a popular and widely-used solution for Kubernetes Ingress.

## Step 1: Install the Nginx Ingress Controller

First, we need to install the `nginx-ingress` controller in our cluster. We can do this by creating a Deployment and a Service that will be responsible for running the Ingress controller.

Create a namespace for the Ingress controller:

```
kubectl create namespace ingress-nginx
```

Install the `nginx-ingress` chart using `kubectl`:

```
kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.7.0/deploy/static/provider/cloud/deploy.yaml
```

Verify that the `nginx-ingress` controller pods are running:

```
kubectl get pods -n ingress-nginx
```

## Step 2: Create a Sample Application

Next, we will create a sample application that we will expose using Ingress. 

Create a Deployment for a sample application:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - name: sample-app
        image: nginx
        ports:
        - containerPort: 80
```

Create a Service for the sample application:

```
apiVersion: v1
kind: Service
metadata:
  name: sample-app
spec:
  selector:
    app: sample-app
  ports:
  - name: http
    port: 80
    targetPort: 80
```

## Step 3: Create an Ingress Resource

Now that we have the Ingress controller set up and a backend service running, we can create the rules for the Ingress resource.

In this example, we will create a simple rule to route traffic for the `example.com` domain to our backend service:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sample-app
            port:
              name: http
```

Apply the Ingress resource to the cluster:

```
kubectl apply -f ingress.yaml
```

## Step 4: Test the Ingress Resource

Finally, we can test the Ingress resource to make sure everything is working correctly. 

First, determine the IP address of the node:

```bash
kubectl get node -o wide
```

This command will get the kubernetes node address, The IP address labeled as `INTERNAL-IP`.

Next, add an entry to your `/etc/hosts` file to map the `example.com` domain to the IP address of the node:

```
echo "<IP_ADDRESS> example.com" | sudo tee -a /etc/hosts
```

Replace `<IP_ADDRESS>` with the internal IP address of the node address.

Then, get service nodeport for `ingress-nginx`.

```bash
kubectl get services -n ingress-nginx
```

This command will dcurisplay a list of services in the `ingress-nginx` namespace. Look for the `nginx-ingress-controller` service and note its `NodePort`.

Finally, use `curl` to make an HTTP request to the Ingress endpoint:

```bash
curl http://example.com:<NodePort>/
```

Replace `<NodePort>` with the `NodePort` of the `nginx-ingress-controller` service.

If everything is set up correctly, you should see the Nginx welcome page.

You can also test the Ingress by using a web browser to visit `http://example.com<NodePort>/nginx`.

Congratulations, you have successfully set up an Ingress resource in Kubernetes and tested it to ensure that it is working correctly.

## Summary
In this lab, we walked through the process of setting up and configuring an Nginx ingress controller in Kubernetes. We also created a sample application and used Ingress to route external traffic to our Nginx service. This is just the beginning of what you can do with Kubernetes networking, and we encourage you to explore further.
