### ISSUE TITLE
lab-run-pods-with-jobs-and-cronjobs

### ISSUE THREAD

**Issue by joker-bai** [labex-labs/scenarios#414]
> **Please read [For Newbie](https://github.com/labex-labs/scenarios/issues/18) first. 请先阅读 [新手须知](https://github.com/labex-labs/scenarios/issues/18)。**

## Basic

> Basic information about the scenario, which can be changed if required.
> 实验/挑战的基本信息，如有需要，可以修改。

- **Suggest Title 建议标题**: Run Pods with Jobs and CronJobs
- **Suggest Steps 建议步骤数**: 3
- **Suggest Image 建议环境**: `vnc-instance-ubuntu:2204`

## Sources

> Issues has provided the material; the part not provided must be completed by the author.
> Issues 已经提供了材料；没有提供的部分由作者自行补充完成。

- [x] Full Text 正文内容
- [ ] Verify Script 检测脚本

## Skills

> Suggested skills to include can be modified as needed. **The main skill points that should be included in this section are bolded**. From [Skills Tree](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp).
> 建议包括的 Skills ID，可以根据需要增删。**本章节应包含的主要技能点已加粗**，技能点来自 [技能树](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp)

- **`kubernetes/apply`**
- `kubernetes/get`
- `kubernetes/logs`

**Comment by joker-bai** [comment]
# Run Pods With Jobs And CronJobs
## Introduction

In Kubernetes, jobs and cronjobs are used to run tasks that are not part of a long-running application or service. Jobs are used for one-off tasks, while cronjobs are used for tasks that need to be run on a regular schedule.

In this lab, we will learn how to run pods with jobs and cronjobs in Kubernetes. We will start with a simple example and gradually build up to more complex examples.

## Step 1: Run a Pod with a Job

The first step is to create a pod that runs a job. In this example, we will create a pod that runs a command to print "Hello, World!" to the console.

Create a file named `job.yaml` with the following contents:

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: hello-job
spec:
  template:
    spec:
      containers:
      - name: hello
        image: busybox
        command: ['sh', '-c', 'echo "Hello, World!"']
      restartPolicy: Never
  backoffLimit: 4
```

In this file, we define a job named `hello-job` that runs a single container named `hello`. The container runs the `busybox` image and executes a command to print "Hello, World!" to the console.

To create the job, run the following command:

```shell
kubectl apply -f job.yaml
```

You can check the status of the job by running the following command:

```shell
kubectl get jobs
```

Once the job is completed, you can view the logs of the pod by running the following command:

```shell
kubectl logs <POD_NAME>
```

Replace `<POD_NAME>` with the name of the pod that ran the job.

Congratulations, you have successfully run a pod with a job in Kubernetes!

## Step 2: Run a Job with Multiple Pods

In some cases, you may need to run a job with multiple pods for better performance. In this example, we will create a job that runs multiple pods to download files from a remote server.

Create a file named `multi-pod-job.yaml` with the following contents:

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: download-job
spec:
  completions: 3
  parallelism: 2
  template:
    spec:
      containers:
      - name: downloader
        image: curlimages/curl
        command: ['curl', '-o', '/data/file', 'http://example.com/file']
        volumeMounts:
        - name: data-volume
          mountPath: /data
      restartPolicy: Never
      volumes:
      - name: data-volume
        emptyDir: {}
  backoffLimit: 4
```

In this file, we define a job named `download-job` that runs multiple pods with the `curlimages/curl` image. Each pod downloads a file from `http://example.com/file` and saves it to a shared volume named `data-volume`.

To create the job, run the following command:

```shell
kubectl apply -f multi-pod-job.yaml
```

You can check the status of the job by running the following command:

```shell
kubectl get jobs
```

Once the job is completed, you can view the logs of the pod by running the following command:

```shell
kubectl logs <POD_NAME>
```

Replace `<POD_NAME>` with the name of any pod that ran the job. You can see the download log of the file.

Congratulations, you have successfully run a job with multiple pods in Kubernetes!

## Step 3: Run a CronJob

In addition to one-off jobs, Kubernetes also supports cronjobs for running tasks on a regular schedule. In this example, we will create a cronjob that runs a command every minute.

Create a file named `cronjob.yaml` with the following contents:

```yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello-cronjob
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            command: ['sh', '-c', 'echo "Hello, World!"']
          restartPolicy: Never
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
```

In this file, we define a cronjob named `hello-cronjob` that runs a command every minute. The command is the same as the one we used in the first example to print "Hello, World!" to the console.

To create the cronjob, run the following command:

```shell
kubectl apply -f cronjob.yaml
```

You can check the status of the cronjob by running the following command:

```shell
kubectl get cronjobs
```

Once the cronjob is running, you can view the logs of the pod by running the following command:

```shell
kubectl logs -f <POD_NAME>
```

Replace `<POD_NAME>` with the name of any pod that was created by the cronjob.

Congratulations, you have successfully run a cronjob in Kubernetes!

## Summary

In this lab, we learned how to run pods with jobs and cronjobs in Kubernetes. We started with a simple example of a pod that runs a job, and gradually built up to more complex examples of jobs with multiple pods and cronjobs that run on a regular schedule. With this knowledge, you can run various tasks that are not part of a long-running application or service in Kubernetes.
