### ISSUE TITLE
lab-containerprobe-in-kubernetes

### ISSUE THREAD

**Issue by joker-bai** [labex-labs/scenarios#415]
> **Please read [For Newbie](https://github.com/labex-labs/scenarios/issues/18) first. 请先阅读 [新手须知](https://github.com/labex-labs/scenarios/issues/18)。**

## Basic

> Basic information about the scenario, which can be changed if required.
> 实验/挑战的基本信息，如有需要，可以修改。

- **Suggest Title 建议标题**: ContainerProbe in Kubernetes
- **Suggest Steps 建议步骤数**: 5
- **Suggest Image 建议环境**: `vnc-instance-ubuntu:2204`

## Sources

> Issues has provided the material; the part not provided must be completed by the author.
> Issues 已经提供了材料；没有提供的部分由作者自行补充完成。

- [x] Full Text 正文内容
- [ ] Verify Script 检测脚本

## Skills

> Suggested skills to include can be modified as needed. **The main skill points that should be included in this section are bolded**. From [Skills Tree](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp).
> 建议包括的 Skills ID，可以根据需要增删。**本章节应包含的主要技能点已加粗**，技能点来自 [技能树](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp)

- **`kubernetes/apply`**
- `kubernetes/get`
- `kubernetes/describe`

**Comment by joker-bai** [comment]
# ContainerProbe in Kubernetes

## Introduction
In Kubernetes, a probe is a diagnostic tool used to determine whether a container is alive and ready to accept traffic. There are two types of probes, liveness probes and readiness probes. In this lab, we will focus on ContainerProbe, which is a tool used to detect when a container is ready to accept traffic.

## Step 1: Create a Deployment
The first step is to create a deployment in Kubernetes. We will use this deployment to test the ContainerProbe.

1. Create a new file named `deployment.yaml`.
2. Copy and paste the following code into the file:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: containerprobe-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: containerprobe
  template:
    metadata:
      labels:
        app: containerprobe
    spec:
      containers:
      - name: containerprobe
        image: nginx
        ports:
        - containerPort: 80
```
This code creates a deployment with one replica, a selector with the label `app: containerprobe`, and a container running the nginx image.

3. Apply the deployment to your cluster:
```bash
kubectl apply -f deployment.yaml
```

## Step 2: Add a Liveness Probe
The next step is to add a liveness probe to the nginx container. A liveness probe is used to determine if the container is alive. If the probe fails, Kubernetes will restart the container.

1. Update the `deployment.yaml` with the follow content:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: containerprobe-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: containerprobe
  template:
    metadata:
      labels:
        app: containerprobe
    spec:
      containers:
      - name: containerprobe
        image: nginx
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
```
This code specifies that the liveness probe should send an HTTP GET request to the root path on port 80.

2. Update the deployment:
```bash
kubectl apply -f deployment.yaml
```

## Step 3: Test the Liveness Probe
Now that we have added a liveness probe, we can test it to see if it is working correctly.

1. Get the pod name:
```bash
kubectl get pods -l app=containerprobe -o jsonpath='{.items[0].metadata.name}'
```
This command gets the name of the pod created by the deployment.

2. Get the status of the liveness probe:

```bash
kubectl describe pod <pod-name>
```
Replace `<pod-name>` with the name of the pod from the previous step.

You should see output that includes the following:

```bash
Liveness: http-get http://:80/ delay=0s timeout=1s period=10s #success=1 #failure=3
```
This indicates that the liveness probe is configured correctly.


## Step 4: Add a Readiness Probe

The next step is to add a readiness probe to the nginx container. A readiness probe is used to determine if the container is ready to accept traffic. If the probe fails, Kubernetes will not send traffic to the container.

1. Add the following code to the container definition in `deployment.yaml`

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: containerprobe-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: containerprobe
  template:
    metadata:
      labels:
        app: containerprobe
    spec:
      containers:
      - name: containerprobe
        image: nginx
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
```
This code specifies that the readiness probe should send an HTTP GET request to the root path on port 80.

2. Update the deployment:

```bash
kubectl apply -f deployment.yaml
```

## Step 5: Test the Readiness Probe
Now that we have added a readiness probe, we can test it to see if it is working correctly.

1. Get the pod name:
```bash
kubectl get pods -l app=containerprobe -o jsonpath='{.items[0].metadata.name}'
```
This command gets the name of the pod created by the deployment.

2. Get the status of the readiness probe:
```bash
kubectl describe pod <pod-name>
```
Replace `<pod-name>` with the name of the pod from the previous step.

You should see output that includes the following:
```
Readiness: http-get http://:80/ delay=0s timeout=1s period=10s #success=1 #failure=3
```
This indicates that the readiness probe is configured correctly.

## Summary
In this lab, we learned how to use ContainerProbe in Kubernetes. We created a deployment, added a liveness probe, tested the liveness probe, added a readiness probe, and tested the readiness probe. By using ContainerProbe, we can ensure that our containers are ready to accept traffic and are functioning correctly.
