### ISSUE TITLE
lab-using-horizontalpodautoscaler-in-kubernetes

### ISSUE THREAD

**Issue by joker-bai** [labex-labs/scenarios#417]
> **Please read [For Newbie](https://github.com/labex-labs/scenarios/issues/18) first. 请先阅读 [新手须知](https://github.com/labex-labs/scenarios/issues/18)。**

## Basic

> Basic information about the scenario, which can be changed if required.
> 实验/挑战的基本信息，如有需要，可以修改。

- **Suggest Title 建议标题**: Using HorizontalPodAutoscaler in Kubernetes
- **Suggest Steps 建议步骤数**: 3
- **Suggest Image 建议环境**: `vnc-instance-ubuntu:2204`

## Sources

> Issues has provided the material; the part not provided must be completed by the author.
> Issues 已经提供了材料；没有提供的部分由作者自行补充完成。

- [x] Full Text 正文内容
- [ ] Verify Script 检测脚本

## Skills

> Suggested skills to include can be modified as needed. **The main skill points that should be included in this section are bolded**. From [Skills Tree](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp).
> 建议包括的 Skills ID，可以根据需要增删。**本章节应包含的主要技能点已加粗**，技能点来自 [技能树](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp)

- **`kubernetes/apply`**
- `kubernetes/get`
- `kubernetes/run`

**Comment by joker-bai** [comment]
# Using HorizontalPodAutoscaler in Kubernetes

## Introduction
HorizontalPodAutoscaler is a Kubernetes feature that allows you to automatically scale the number of pods in a deployment based on resource utilization. In this lab, we will learn how to use HorizontalPodAutoscaler to automatically scale our deployment.

## Step 1: Create a Deployment
First, we need to create a deployment to which we will apply the HorizontalPodAutoscaler.

1. Create a deployment file named `deployment.yaml` with the following contents:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpa-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hpa-demo
  template:
    metadata:
      labels:
        app: hpa-demo
    spec:
      containers:
      - name: hpa-demo
        image: nginx
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: "0.5"
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: hpa-demo
spec:
  selector:
    app: hpa-demo
  ports:
  - name: http
    port: 80
    targetPort: 80
```
This deployment specifies a single replica of an Nginx container with resource limits and requests for CPU and memory.

2. Create the deployment:
```bash
$ kubectl apply -f deployment.yaml
```

## Step 2: Create a HorizontalPodAutoscaler
Now that we have a deployment, we can create a HorizontalPodAutoscaler to automatically scale the deployment.

1. Create a HorizontalPodAutoscaler file named `hpa.yaml` with the following contents:
```yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-demo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hpa-demo
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        averageUtilization: 1
        type: Utilization
```
This HorizontalPodAutoscaler specifies that we want to scale the `hpa-demo` deployment to have between 1 and 10 replicas, and that we want to target an average CPU utilization of 50%.

2. Create the HorizontalPodAutoscaler:
```bash
$ kubectl apply -f hpa.yaml
```

## Step 3: Test the HorizontalPodAutoscaler
Now that we have a HorizontalPodAutoscaler, we can test it by generating load on the deployment.

1. Enable the metrice-server

```bash
minikube addons enable metrics-server
```

2. Create a load generation pod:
```bash
$ kubectl run -i --tty load-generator --image=busybox /bin/sh
```

3. In the load generation pod, run the following command to generate load on the deployment:
```bash
$ while true; do wget -q -O- http://hpa-demo; done
```
4. Open another terminal, check the status of the HorizontalPodAutoscaler:
```bash
$ kubectl get hpa
```

You can see that the number of copies of `hpa-demo` has been extended to `10`. You can check the number of replicas with the following command.

```bash
kubectl get pods -l app=hpa-demo
```

5. Stop the load generation by typing `ctrl+c` in the load generation pod.

## Summary
In this lab, we learned how to use HorizontalPodAutoscaler to automatically scale a deployment based on resource utilization. We created a deployment, created a HorizontalPodAutoscaler, and tested it by generating load on the deployment. We also saw how the HorizontalPodAutoscaler scaled the deployment in response to the increased load.
