### ISSUE TITLE
lab-kubernetes-describe-command

### ISSUE THREAD

**Issue by joker-bai** [labex-labs/scenarios#423]
> **Please read [For Newbie](https://github.com/labex-labs/scenarios/issues/18) first. 请先阅读 [新手须知](https://github.com/labex-labs/scenarios/issues/18)。**

## Basic

> Basic information about the scenario, which can be changed if required.
> 实验/挑战的基本信息，如有需要，可以修改。

- **Suggest Title 建议标题**: Kubernetes Describe Command
- **Suggest Steps 建议步骤数**: 3
- **Suggest Image 建议环境**: `vnc-instance-ubuntu:2204`

## Sources

> Issues has provided the material; the part not provided must be completed by the author.
> Issues 已经提供了材料；没有提供的部分由作者自行补充完成。

- [x] Full Text 正文内容
- [ ] Verify Script 检测脚本

## Skills

> Suggested skills to include can be modified as needed. **The main skill points that should be included in this section are bolded**. From [Skills Tree](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp).
> 建议包括的 Skills ID，可以根据需要增删。**本章节应包含的主要技能点已加粗**，技能点来自 [技能树](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp)

- **`kubernetes/describe`**
- `kubernetes/apply`

**Comment by joker-bai** [comment]
# Kubernetes Describe Command

## Introduction

The Kubernetes `describe` command is a powerful tool for viewing detailed information about Kubernetes resources. With the `describe` command, you can view information such as resource status, events, labels, annotations, and more. This can be useful for troubleshooting issues in your Kubernetes cluster.

## Step 1: Describe a Pod

In this step, you will learn how to use the `describe` command to view information about a Kubernetes Pod.

1. Create a simple pod that will be used as the template for the replicas. Create a file called `myapp-pod.yaml` with the following contents:

	```yaml
	apiVersion: v1
	kind: Pod
	metadata:
	  name: myapp-pod
	spec:
	  containers:
	  - name: myapp-container
	    image: nginx
	    ports:
	    - containerPort: 80
	```

	Create the pod using the following command:
	
	```shell
	kubectl apply -f myapp-pod.yaml
	```

2. Then describe the pod:

	```bash
	kubectl describe pod myapp-pod
	```

This command will retrieve detailed information about the specified Pod, including status, labels, annotations, events, and more.

## Step 2: Describe a Deployment

In this step, you will learn how to use the `describe` command to view information about a Kubernetes Deployment.

1. Create a file called `myapp-deployment.yaml` with the following content:

	```yaml
	apiVersion: apps/v1
	kind: Deployment
	metadata:
	  name: myapp-deployment
	spec:
	  replicas: 1
	  selector:
	    matchLabels:
	      app: myapp-deployment
	  template:
	    metadata:
	      labels:
	        app: myapp-deployment
	    spec:
	      containers:
	      - name: myapp-container
	        image: nginx:latest
	        ports:
	        - containerPort: 80
	```
	
	Create the deployment using the following command:
	
	```bash
	kubectl apply -f myapp-deployment.yaml
	```

2. Describe the deployment:

	```bash
	kubectl describe deployment myapp-deployment
	```

This command will retrieve detailed information about the specified Deployment, including status, labels, annotations, events, and more.

## Step 3: Describe a Service

In this step, you will learn how to use the `describe` command to view information about a Kubernetes Service.

1.  Create a file called `myapp-service.yaml` with the following content:

	```yaml
	apiVersion: v1
	kind: Service
	metadata:
	  name: myapp-service
	spec:
	  selector:
	    app: myapp-deployment
	  ports:
	  - protocol: TCP
	    port: 80
	    targetPort: 80
	```

	Create the service using the following command:
	
	```bash
	kubectl apply -f myapp-service.yaml
	```

2. Use the following command to describe the service:

	```bash
	kubectl describe service myapp-service
	```

This command will retrieve detailed information about the specified Service, including status, labels, annotations, events, and more.

## Summary

In this lab, you learned how to use the Kubernetes `describe` command to view detailed information about Kubernetes resources. You learned how to describe a Pod, Deployment, Service, and StatefulSet, and how to use the `describe` command to troubleshoot issues in your Kubernetes cluster.
