### ISSUE TITLE
lab-kubernetes-create-command

### ISSUE THREAD

**Issue by joker-bai** [labex-labs/scenarios#436]
> **Please read [For Newbie](https://github.com/labex-labs/scenarios/issues/18) first. 请先阅读 [新手须知](https://github.com/labex-labs/scenarios/issues/18)。**

## Basic

> Basic information about the scenario, which can be changed if required.
> 实验/挑战的基本信息，如有需要，可以修改。

- **Suggest Title 建议标题**: Kubernetes Create Command
- **Suggest Steps 建议步骤数**: 5
- **Suggest Image 建议环境**: `vnc-instance-ubuntu:2204`

## Sources

> Issues has provided the material; the part not provided must be completed by the author.
> Issues 已经提供了材料；没有提供的部分由作者自行补充完成。

- [x] Full Text 正文内容
- [ ] Verify Script 检测脚本

## Skills

> Suggested skills to include can be modified as needed. **The main skill points that should be included in this section are bolded**. From [Skills Tree (Click to apply for permission after logging in)](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp).
> 建议包括的 Skills ID，可以根据需要增删。**本章节应包含的主要技能点已加粗**，技能点来自 [技能树 (登录后点击申请权限)](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp)

- **`kubernetes/create`**
- `kubernetes/get`

**Comment by joker-bai** [comment]
# Kubernetes Create Command

## Introduction

The `kubectl create` command is used to create Kubernetes resources. It takes a resource definition file as input and creates the resource in the Kubernetes cluster. The resource definition file can be in YAML or JSON format. In this lab, we will be using YAML format.

## Create a Namespace

The first step is to create a namespace. A namespace is a way to divide cluster resources between multiple users. To create a namespace, create a file called `namespace.yaml` with the following contents:

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: mynamespace
```

Then, run the following command to create the namespace:

```bash
kubectl create -f namespace.yaml
```

This will create a namespace called `mynamespace`. You can verify that the namespace was created by running the following command:

```bash
kubectl get namespaces
```

This will display a list of namespaces, including the `mynamespace` namespace.

## Create a Deployment

The next step is to create a deployment. A deployment manages a set of replicas of a pod template. To create a deployment, create a file called `deployment.yaml` with the following contents:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
  namespace: mynamespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: mycontainer
          image: nginx
```

Then, run the following command to create the deployment:

```bash
kubectl create -f deployment.yaml
```

This will create a deployment called `mydeployment` in the `mynamespace` namespace. The deployment will manage 3 replicas of a pod template that runs an Nginx container.

You can verify that the deployment was created by running the following command:

```bash
kubectl get deployments -n mynamespace
```

This will display a list of deployments, including the `mydeployment` deployment.

## Create a Service

The next step is to create a service. A service is an abstract way to expose an application running on a set of pods as a network service. To create a service, create a file called `service.yaml` with the following contents:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: myservice
  namespace: mynamespace
spec:
  selector:
    app: myapp
  ports:
    - name: http
      port: 80
      targetPort: 80
```

Then, run the following command to create the service:

```bash
kubectl create -f service.yaml
```

This will create a service called `myservice` in the `mynamespace` namespace. The service will select pods with the label `app=myapp` and expose port 80.

You can verify that the service was created by running the following command:

```bash
kubectl get services -n mynamespace
```

This will display a list of services, including the `myservice` service.

## Create a Secret

The next step is to create a secret. A secret is an object that contains sensitive data, such as passwords or API keys. To create a secret, create a file called `secret.yaml` with the following contents:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: mynamespace
type: Opaque
data:
  username: dXNlcm5hbWU=
  password: cGFzc3dvcmQ=
```

In this example, we are creating a secret called `mysecret` in the `mynamespace` namespace. The secret contains a username and password encoded in Base64 format.

To create the secret, run the following command:

```bash
kubectl create -f secret.yaml
```

You can verify that the secret was created by running the following command:

```bash
kubectl get secrets -n mynamespace
```

This will display a list of secrets, including the `mysecret` secret.

## Create a ConfigMap

The final step is to create a configMap. A configMap is an object that contains configuration data that can be consumed by pods. To create a configMap, create a file called `configmap.yaml` with the following contents:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfigmap
  namespace: mynamespace
data:
  config: |
    database.host=example.com
    database.port=5432
    database.user=myuser
    database.password=mypassword
```

In this example, we are creating a configMap called `myconfigmap` in the `mynamespace` namespace. The configMap contains a configuration file that can be consumed by pods.

To create the configMap, run the following command:

```bash
kubectl create -f configmap.yaml
```

You can verify that the configMap was created by running the following command:

```bash
kubectl get configmaps -n mynamespace
```

This will display a list of configMaps, including the `myconfigmap` configMap.

## Summary

Congratulations! In this lab, you learned how to use the `kubectl create` command to create various Kubernetes resources. You started with simple examples and gradually moved on to more complex examples, including creating a namespace, deployment, service, secret, and configMap. Now you have a good understanding of how to use the `kubectl create` command to create Kubernetes resources.
