### ISSUE TITLE
lab-scheduing-with-node-affinity

### ISSUE THREAD

**Issue by joker-bai** [labex-labs/scenarios#488]
> **Please read [For Newbie](https://github.com/labex-labs/scenarios/issues/18) first. 请先阅读 [新手须知](https://github.com/labex-labs/scenarios/issues/18)。**

## Basic

> Basic information about the scenario, which can be changed if required.
> 实验/挑战的基本信息，如有需要，可以修改。

- **Suggest Title 建议标题**: Scheduing with Node Affinity
- **Suggest Steps 建议步骤数**: 5
- **Suggest Image 建议环境**: `webide-instance-ubuntu:2204`

## Sources

> Issues has provided the material; the part not provided must be completed by the author.
> Issues 已经提供了材料；没有提供的部分由作者自行补充完成。

- [x] Full Text 正文内容
- [ ] Verify Script 检测脚本

## Skills

> Suggested skills to include can be modified as needed. **The main skill points that should be included in this section are bolded**. From [Skills Tree (Click to apply for permission after logging in)](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp).
> 建议包括的 Skills ID，可以根据需要增删。**本章节应包含的主要技能点已加粗**，技能点来自 [技能树 (登录后点击申请权限)](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp)

- **`kubernetes/apply`**
- `kubernetes/get`

**Comment by joker-bai** [comment]
# Scheduing with Node Affinity

## Introduction

In Kubernetes, node affinity is used to schedule pods on nodes that match certain conditions. This can be used to ensure that pods are scheduled on specific types of nodes, or to balance the workload across nodes. In this lab, we will learn how to use node affinity to schedule pods on specific nodes.

## Creating a Node with Labels

In this step, we will create a node with a label that will be used to schedule pods.

1. Create a file named `node-with-label.yaml` with the following contents:

```yaml
apiVersion: v1
kind: Node
metadata:
  name: minikube
  labels:
    type: web
```

2. Apply the changes:

```bash
kubectl apply -f node-with-label.yaml
```

3. Verify that the node has been created and labeled:

```bash
kubectl get nodes --show-labels
```

## Creating a Pod with Node Affinity

In this step, we will create a pod with a node affinity rule that will ensure it is scheduled on a node with a specific label.

1. Create a file named `pod-with-node-affinity.yaml` with the following contents:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-node-affinity
spec:
  containers:
    - name: nginx
      image: nginx:latest
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: type
                operator: In
                values:
                  - web
```

2. Apply the changes:

```bash
kubectl apply -f pod-with-node-affinity.yaml
```

3. Verify that the pod is scheduled on the node with the `type=web` label:

```bash
kubectl get pod pod-with-node-affinity -o wide
```

## Creating a Pod with Node Anti-Affinity

In this step, we will create a pod with a node anti-affinity rule that will ensure it is not scheduled on a node with a specific label.

1. Create a file named `pod-with-node-anti-affinity.yaml` with the following contents:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-node-anti-affinity
spec:
  containers:
    - name: nginx
      image: nginx:latest
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: type
                operator: NotIn
                values:
                  - web
```

2. Apply the changes:

```bash
kubectl apply -f pod-with-node-anti-affinity.yaml
```

3. Verify that the pod is not scheduled on the node with the `type=db` label:

```bash
kubectl get pod pod-with-node-anti-affinity -o wide
```

## Creating a Pod with Node Affinity and Node Selector

In this step, we will create a pod with both a node affinity rule and a node selector that will ensure it is scheduled on a node with a specific label.

1. Create a file named `pod-with-node-affinity-and-selector.yaml` with the following contents:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-node-affinity-and-selector
spec:
  containers:
    - name: nginx
      image: nginx:latest
  nodeSelector:
    type: web
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: type
                operator: In
                values:
                  - db
```

2. Apply the changes:

```bash
kubectl apply -f pod-with-node-affinity-and-selector.yaml
```

3. Verify that the pod is scheduled on the node with the `type=web` label:

```bash
kubectl get pod pod-with-node-affinity-and-selector -o wide
```

## Creating a Pod with Multiple Node Affinity Rules

In this step, we will create a pod with multiple node affinity rules that will ensure it is scheduled on a node with labels that match all of the rules.

1. Create a file named `pod-with-multiple-node-affinity.yaml` with the following contents:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-multiple-node-affinity
spec:
  containers:
    - name: nginx
      image: nginx:latest
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: type
                operator: In
                values:
                  - web
          - matchExpressions:
              - key: disktype
                operator: In
                values:
                  - ssd
```

2. Apply the changes:

```bash
kubectl apply -f pod-with-multiple-node-affinity.yaml
```

3. Verify that the pod is scheduled on the node with the `type=web` and `disktype=ssd` labels:

```bash
kubectl get pod pod-with-multiple-node-affinity -o wide
```

## Summary

In this lab, we learned how to use node affinity to schedule pods on specific nodes. We created a node with a label, and then created pods with node affinity rules that ensured they were scheduled on nodes with specific labels. We also created a pod with a node anti-affinity rule that ensured it was not scheduled on a node with a specific label. Finally, we created a pod with multiple node affinity rules that ensured it was scheduled on a node with labels that matched all of the rules.
