### ISSUE TITLE
lab-scheduing-with-pod-affinity

### ISSUE THREAD

**Issue by joker-bai** [labex-labs/scenarios#489]
> **Please read [For Newbie](https://github.com/labex-labs/scenarios/issues/18) first. 请先阅读 [新手须知](https://github.com/labex-labs/scenarios/issues/18)。**

## Basic

> Basic information about the scenario, which can be changed if required.
> 实验/挑战的基本信息，如有需要，可以修改。

- **Suggest Title 建议标题**:  Scheduling with Pod Affinity
- **Suggest Steps 建议步骤数**: 4
- **Suggest Image 建议环境**: `webide-instance-ubuntu:2204`

## Sources

> Issues has provided the material; the part not provided must be completed by the author.
> Issues 已经提供了材料；没有提供的部分由作者自行补充完成。

- [x] Full Text 正文内容
- [ ] Verify Script 检测脚本

## Skills

> Suggested skills to include can be modified as needed. **The main skill points that should be included in this section are bolded**. From [Skills Tree (Click to apply for permission after logging in)](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp).
> 建议包括的 Skills ID，可以根据需要增删。**本章节应包含的主要技能点已加粗**，技能点来自 [技能树 (登录后点击申请权限)](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp)

- **`kubernetes/apply`**
- `kubernetes/get`

**Comment by joker-bai** [comment]
# Scheduling with Pod Affinity

## Introduction

Pod affinity is a Kubernetes feature that allows us to influence the scheduling of pods based on the presence or absence of other pods. In this lab, we will learn how to use pod affinity to schedule pods together on the same node or on nodes that share a certain label.

## Creating a Pod with Labels

In this step, we will create a pod with a label that we will use to demonstrate pod affinity.

1. Create a file named `pod-with-label.yaml` with the following contents:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-label
  labels:
    app: web
spec:
  containers:
    - name: nginx
      image: nginx:latest
```

2. Apply the changes:

```bash
kubectl apply -f pod-with-label.yaml
```

## Creating a Pod with Pod Affinity

In this step, we will create a pod with a pod affinity rule that will ensure it is scheduled on the same node as the pod we created in step 1.

1. Create a file named `pod-with-pod-affinity.yaml` with the following contents:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-pod-affinity
spec:
  containers:
    - name: nginx
      image: nginx:latest
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - web
          topologyKey: "kubernetes.io/hostname"
```

2. Apply the changes:

```bash
kubectl apply -f pod-with-pod-affinity.yaml
```

3. Verify that the pod is scheduled on the same node as the pod created in step 1:

```bash
kubectl get pod pod-with-pod-affinity -o wide
```

## Creating a Pod with Anti-Affinity

In this step, we will create a pod with an anti-affinity rule that will ensure it is not scheduled on the same node as the pod we created in step 1.

1. Create a file named `pod-with-anti-affinity.yaml` with the following contents:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-anti-affinity
spec:
  containers:
    - name: nginx
      image: nginx:latest
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - web
          topologyKey: "kubernetes.io/hostname"
```

2. Apply the changes:

```bash
kubectl apply -f pod-with-anti-affinity.yaml
```

3. Verify that the pod is not scheduled on the same node as the pod created in step 1:

```bash
kubectl get pod pod-with-anti-affinity -o wide
```

## Creating a Pod with Node Affinity and Pod Affinity

In this step, we will create a pod with both a node affinity rule and a pod affinity rule that will ensure it is scheduled on a node with a specific label and on the same node as the pod we created in step 1.

1. Create a file named `pod-with-node-and-pod-affinity.yaml` with the following contents:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-node-and-pod-affinity
spec:
  containers:
    - name: nginx
      image: nginx:latest
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - web
          topologyKey: "kubernetes.io/hostname"
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: type
                operator: In
                values:
                  - web
```

2. Apply the changes:

```bash
kubectl apply -f pod-with-node-and-pod-affinity.yaml
```

3. Verify that the pod is scheduled on the node with the `type=web` label and on the same node as the pod created in step 1:

```bash
kubectl get pod pod-with-node-and-pod-affinity -o wide
```

## Summary

In this lab, we learned how to use pod affinity to influence the scheduling of pods based on the presence or absence of other pods or labels on nodes. We created pods with pod affinity, anti-affinity, node affinity, and combinations of both. Pod affinity is a powerful feature of Kubernetes that can be used to optimize the performance and resource utilization of our workloads.
