### ISSUE TITLE
lab-scheduing-with-node-selectors

### ISSUE THREAD

**Issue by joker-bai** [labex-labs/scenarios#490]
> **Please read [For Newbie](https://github.com/labex-labs/scenarios/issues/18) first. 请先阅读 [新手须知](https://github.com/labex-labs/scenarios/issues/18)。**

## Basic

> Basic information about the scenario, which can be changed if required.
> 实验/挑战的基本信息，如有需要，可以修改。

- **Suggest Title 建议标题**: Scheduling with Node Selectors
- **Suggest Steps 建议步骤数**: 3
- **Suggest Image 建议环境**: `webide-instance-ubuntu:2204`

## Sources

> Issues has provided the material; the part not provided must be completed by the author.
> Issues 已经提供了材料；没有提供的部分由作者自行补充完成。

- [x] Full Text 正文内容
- [ ] Verify Script 检测脚本

## Skills

> Suggested skills to include can be modified as needed. **The main skill points that should be included in this section are bolded**. From [Skills Tree (Click to apply for permission after logging in)](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp).
> 建议包括的 Skills ID，可以根据需要增删。**本章节应包含的主要技能点已加粗**，技能点来自 [技能树 (登录后点击申请权限)](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp)

- **`kubernetes/apply`**
- `kubernetes/get`

**Comment by joker-bai** [comment]
# Scheduling with Node Selectors

## Introduction

In this lab, we will start by creating a simple deployment and then assign Node Selectors to it. We will then move on to more complex scenarios where we will use different selectors to schedule pods on specific nodes.

## Creating a Simple Deployment

In this step, we will create a simple deployment with a single pod.

1. Create a file named `simple-deployment.yaml` with the following contents:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-app
  template:
    metadata:
      labels:
        app: simple-app
    spec:
      containers:
        - name: simple-container
          image: nginx:latest
```

2. Use `kubectl` to create the deployment:

```bash
kubectl apply -f simple-deployment.yaml
```

3. Verify that the deployment has been created:

```bash
kubectl get deployments
```

## Assigning Node Selectors to a Deployment

In this step, we will assign a Node Selector to the deployment we created in Step 1.

1. Create the nodes with a label:

```bash
kubectl label nodes minikube disk=ssd
```

1. Edit the `node-selector-deployment.yaml` file and add the `nodeSelector` field under the `spec.template.spec` section:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-app
  template:
    metadata:
      labels:
        app: simple-app
    spec:
      nodeSelector:
        disk: ssd
      containers:
        - name: simple-container
          image: nginx:latest
```

2. Use `kubectl` to apply the changes:

```bash
kubectl apply -f node-selector-deployment.yaml
```

3. Verify that the pod has been scheduled on a node with the label `disk=ssd`:

```bash
kubectl get pods -o wide
```

## Using Different Node Selectors

In this step, we will use different Node Selectors to schedule pods on specific nodes based on the labels assigned to those nodes.

1. Create three nodes with different labels:

```bash
kubectl label nodes minikube resigon=labex
kubectl label nodes minikube gpu=true
```

2. Create a file named `multi-selector-deployment.yaml` with the following contents:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-selector-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: multi-selector-app
  template:
    metadata:
      labels:
        app: multi-selector-app
    spec:
      containers:
        - name: multi-selector-container
          image: nginx:latest
      nodeSelector:
        resigon: labex
        gpu: "true"
```

3. Apply the changes:

```bash
kubectl apply -f multi-selector-deployment.yaml
```

4. Verify that the pods have been scheduled on nodes with the appropriate labels:

```bash
kubectl get pods -o wide
```

## Summary

In this lab, we learned how to schedule pods on specific nodes using Node Selectors and Node Affinity. We started with a simple deployment and then moved on to more complex scenarios where we used different selectors and affinity rules to schedule pods on specific nodes based on the labels assigned to those nodes.

Congratulations! You have successfully completed this lab.
