### ISSUE TITLE
lab-taints-and-tolerations

### ISSUE THREAD

**Issue by joker-bai** [labex-labs/scenarios#491]
> **Please read [For Newbie](https://github.com/labex-labs/scenarios/issues/18) first. 请先阅读 [新手须知](https://github.com/labex-labs/scenarios/issues/18)。**

## Basic

> Basic information about the scenario, which can be changed if required.
> 实验/挑战的基本信息，如有需要，可以修改。

- **Suggest Title 建议标题**: Taints and tolerations
- **Suggest Steps 建议步骤数**: 4
- **Suggest Image 建议环境**: `webide-instance-ubuntu:2204`

## Sources

> Issues has provided the material; the part not provided must be completed by the author.
> Issues 已经提供了材料；没有提供的部分由作者自行补充完成。

- [x] Full Text 正文内容
- [ ] Verify Script 检测脚本

## Skills

> Suggested skills to include can be modified as needed. **The main skill points that should be included in this section are bolded**. From [Skills Tree (Click to apply for permission after logging in)](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp).
> 建议包括的 Skills ID，可以根据需要增删。**本章节应包含的主要技能点已加粗**，技能点来自 [技能树 (登录后点击申请权限)](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp)

- **`kubernetes/apply`**
- `kubernetes/label`
- `kubernetes/get`

**Comment by joker-bai** [comment]
# Taints and tolerations

## Introduction

Taints and tolerations are used in Kubernetes to specify which nodes are suitable for scheduling certain pods. Taints are applied to nodes to repel pods, while tolerations are applied to pods to attract them to specific nodes. In this lab, we will learn how to use taints and tolerations to schedule pods on specific nodes.

## Creating a Tainted Node

In this step, we will create a node with a taint that will repel certain pods.

1. Label a node with a custom label:

```bash
kubectl label nodes minikube disk-type=ssd
```

2. Taint the node with the following command:

```bash
kubectl taint nodes minikube disk-type=ssd:NoSchedule
```

The `NoSchedule` effect will prevent pods without tolerations from being scheduled on this node.

## Creating a Pod without Tolerations

In this step, we will create a pod without tolerations and verify that it cannot be scheduled on the tainted node.

1. Create a file named `pod-without-toleration.yaml` with the following contents:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: pod-without-toleration
spec:
  containers:
    - name: nginx
      image: nginx:latest
```

2. Apply the changes:

```bash
kubectl apply -f pod-without-toleration.yaml
```

3. Verify that the pod is not scheduled on the tainted node:

```bash
kubectl describe pod pod-without-toleration | grep -i taint
```

The output should show that the pod is not scheduled on the node with the taint.

## Creating a Pod with Tolerations

In this step, we will create a pod with tolerations that will allow it to be scheduled on the tainted node.

1. Create a file named `pod-with-toleration.yaml` with the following contents:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-toleration
spec:
  containers:
    - name: nginx
      image: nginx:latest
  tolerations:
    - key: "disk-type"
      operator: "Equal"
      value: "ssd"
      effect: "NoSchedule"
```

2. Apply the changes:

```bash
kubectl apply -f pod-with-toleration.yaml
```

3. Verify that the pod is scheduled on the tainted node:

```bash
kubectl get pod pod-with-toleration -o wide
```

## Tolerating Multiple Taints

In this step, we will create a pod with multiple tolerations that will allow it to be scheduled on nodes with multiple taints.

1. Create a file named `pod-with-multiple-tolerations.yaml` with the following contents:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-multiple-tolerations
spec:
  containers:
    - name: nginx
      image: nginx:latest
  tolerations:
    - key: "disk-type"
      operator: "Equal"
      value: "ssd"
      effect: "NoSchedule"
    - key: "gpu"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
```

2. Apply the changes:

```bash
kubectl apply -f pod-with-multiple-tolerations.yaml
```

3. Verify that the pod is scheduled on a node with both taints:

```bash
kubectl get pod pod-with-multiple-tolerations
```

## Summary

In this lab, we learned how to use taints and tolerations to schedule pods on specific nodes. We started by creating a tainted node and verifying that pods without tolerations could not be scheduled on it. We then created a pod with tolerations and verified that it could be scheduled on the tainted node. Finally, we created a pod with multiple tolerations and verified that it could be scheduled on nodes with multiple taints.

Taints and tolerations are a powerful feature of Kubernetes that can be used to ensure that certain workloads are only scheduled on specific nodes.
