### ISSUE TITLE
challenge-running-containers-in-pods

### ISSUE THREAD

**Issue by joker-bai** [labex-labs/scenarios#677]
> **Please read [For Newbie](https://github.com/labex-labs/scenarios/issues/18) first. 请先阅读 [新手须知](https://github.com/labex-labs/scenarios/issues/18)。**

## Basic

> Basic information about the scenario, which can be changed if required.
> 实验/挑战的基本信息，如有需要，可以修改。

- **Suggest Title 建议标题**:  Running Containers in Pods
- **Suggest Steps 建议步骤数**: 5
- **Suggest Image 建议环境**: `webide-instance-ubuntu:2204`

## Sources

> Issues has provided the material; the part not provided must be completed by the author.
> Issues 已经提供了材料；没有提供的部分由作者自行补充完成。

- [x] Full Text 正文内容
- [x] Reference Answers 参考答案
- [ ] Verify Script 检测脚本

## Skills

> Suggested skills to include can be modified as needed. **The main skill points that should be included in this section are bolded**. From [Skills Tree (Click to apply for permission after logging in)](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp).
> 建议包括的 Skills ID，可以根据需要增删。**本章节应包含的主要技能点已加粗**，技能点来自 [技能树 (登录后点击申请权限)](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp)

- **`kubernetes/apply`**
- `kubernetes/create`
- `kubernetes/get`

**Comment by joker-bai** [comment]
# Running Containers in Pods

## Introduction

In this lab, you will learn how to run containers in Kubernetes Pods. Pods are the smallest and simplest unit in Kubernetes, and they can contain one or more containers. Running containers in Pods provides many benefits, including better resource utilization, easier scaling, and more efficient deployment.

## Step 1: Create a Pod with a Single Container

### Introduction

In this lab, we will learn how to create a Pod with a single container in Kubernetes.

### Target

Your goal is to deploy a Pod in your Kubernetes cluster with the `nginx:latest` image and the name called `my-pod`.

### Result Example

Here is an example of what you should be able to accomplish at the end of this step:

1. Create a Pod YAML file called `pod-single-container.yaml` on the `Target`.
2. Run the `kubectl apply` command to deploy the pod.

### Solution

The first step is to create a Pod with a single container. To do this, you will create a YAML file that defines the Pod and its container.

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: my-container
      image: nginx
```

Save the above code in a file named `pod-single-container.yaml` and execute the following command:

```bash
kubectl apply -f pod-single-container.yaml
```

This command will create a Pod named `my-pod` with a single container named `my-container` that runs the Nginx image.

### Requirements

To complete this challenge, you will need:

- A Kubernetes cluster has been installed and configured as required.

## Step 2: Create a Pod with Multiple Containers

### Introduction

In this tutorial, we will explore how to create a Pod with multiple containers in Kubernetes.

### Target

Your goal is to create a multi-container Pod with one container using the `nginx:latest` image and the other container using the `busybox:latest` image.

### Result Example

Here is an example of what you should be able to accomplish at the end of this step:

1. Create a Pod YAML file called `pod-multiple-containers.yaml` on the `Target`.
2. Run the `kubectl apply` command to deploy the pod.

### Solution

The second step is to create a Pod with multiple containers. To do this, you will modify the previous YAML file to add another container.

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: my-container
      image: nginx
    - name: my-sidecar
      image: busybox
      command: ["sh", "-c", "echo Hello from the sidecar! && sleep 3600"]
```

Save the above code in a file named `pod-multiple-containers.yaml` and execute the following command:

```bash
kubectl apply -f pod-multiple-containers.yaml
```

This command will create a Pod named `my-pod` with two containers. The first container runs the Nginx image, and the second container runs the BusyBox image and prints a message to the console.

### Requirements

To complete this challenge, you will need:

- A Kubernetes cluster has been installed and configured as required.

## Step 3: Create a Pod with Environment Variables

### Introduction

In this lab, we will learn how to create a Pod with environment variables in Kubernetes. Environment variables are a powerful way to pass configuration information to containers at runtime.

### Target

Your goal is to create a Pod with an environment variable via `nginx:latest` with a Key of `MY_ENV_VAR` and a value of `Hello World!`.

### Result Example

Here is an example of what you should be able to accomplish at the end of this step:

1. Create a Pod YAML file called `pod-env-vars.yaml` on the `Target`.
2. Run the `kubectl apply` command to deploy the pod.

### Solution

The third step is to create a Pod with environment variables. To do this, you will modify the YAML file to add environment variables to the Nginx container.

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: my-container
      image: nginx
      env:
        - name: MY_ENV_VAR
          value: "Hello World!"
```

Save the above code in a file named `pod-env-vars.yaml` and execute the following command:

```bash
kubectl apply -f pod-env-vars.yaml
```

This command will create a Pod named `my-pod` with a single container named `my-container` that runs the Nginx image and has an environment variable named `MY_ENV_VAR` with the value `Hello World!`.

### Requirements

To complete this challenge, you will need:

- A Kubernetes cluster has been installed and configured as required.

## Step 4: Create a Pod with ConfigMaps

### Introduction

In this lab, we will explore how to create a Pod with ConfigMaps in Kubernetes. ConfigMaps are a powerful way to manage configuration data separately from application code.

### Target

Your goal is to create a ConfigMap called `my-config` and also create a Pod to use it.

### Result Example

Here is an example of what you should be able to accomplish at the end of this step:

1. Use `kubectl create configmap` command to Create a ConfigMap named `my-config` with a Key of `my-key` and a value of `my-value`.
1. Create a Pod YAML file called `pod-configmap.yaml`, the pod need to use the created ConfigMap.
1. Run the `kubectl apply` command to deploy the pod.

### Solution

The fourth step is to create a Pod with ConfigMaps. ConfigMaps are a way to store configuration data separately from the application code.

To do this, you will first create a ConfigMap with some data.

```bash
kubectl create configmap my-config --from-literal=my-key=my-value
```

This command will create a ConfigMap named `my-config` with a key `my-key` and a value `my-value`.

Next, you will modify the YAML file to add the ConfigMap to the Nginx container.

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: my-container
      image: nginx
      envFrom:
        - configMapRef:
            name: my-config
```

Save the above code in a file named `pod-configmap.yaml` and execute the following command:

```bash
kubectl apply -f pod-configmap.yaml
```

This command will create a Pod named `my-pod` with a single container named `my-container` that runs the Nginx image and has a ConfigMap named `my-config` injected as environment variables.

### Requirements

To complete this challenge, you will need:

- A Kubernetes cluster has been installed and configured as required.

## Step 5: Create a Pod with Persistent Volumes

### Introduction

In this lab, we will learn how to create a Pod with Persistent Volumes in Kubernetes. Persistent Volumes are a powerful way to store and manage data separately from the Pod lifecycle.

### Target

Your goal is to create a PV and a PVC, then use the Pod to mount it.

### Result Example

Here is an example of what you should be able to accomplish at the end of this step:

1. Create a PV named `my-pv` with a capacity of 1Gi and a host path of `/mnt/data`.
2. Create a PVC that requests 1Gi of storage from the PV
3. Create a Pod named `my-pod` with a single container named `my-container` that runs the Nginx image and has a volume mount at `/mnt/data` that is backed by the PVC named `my-pvc`.

### Solution

The fifth step is to create a Pod with a Persistent Volume (PV) and a Persistent Volume Claim (PVC). PVs and PVCs are used to store and access data persistently across Pod restarts.

To do this, you will first create a PV.

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
```

Save the above code in a file named `pv.yaml` and execute the following command:

```bash
kubectl apply -f pv.yaml
```

This command will create a PV named `my-pv` with a capacity of 1Gi and a host path of `/mnt/data`.

Next, you will create a PVC that requests 1Gi of storage from the PV.

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
```

Save the above code in a file named `pvc.yaml` and execute the following command:

```bash
kubectl apply -f pvc.yaml
```

This command will create a PVC named `my-pvc` that requests 1Gi of storage.

Finally, you will modify the YAML file to add a volume and a volume mount to the Nginx container.

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: my-container
      image: nginx
      volumeMounts:
        - name: my-volume
          mountPath: /mnt/data
  volumes:
    - name: my-volume
      persistentVolumeClaim:
        claimName: my-pvc
```

Save the above code in a file named `pod-pv.yaml` and execute the following command:

```bash
kubectl apply -f pod-pv.yaml
```

This command will create a Pod named `my-pod` with a single container named `my-container` that runs the Nginx image and has a volume mount at `/mnt/data` that is backed by the PVC named `my-pvc`.

### Requirements

To complete this challenge, you will need:

- A Kubernetes cluster has been installed and configured as required.

## Summary

Congratulations! You have completed this lab and learned how to run containers in Kubernetes Pods. You have also learned how to create Pods with multiple containers, environment variables, ConfigMaps, and Persistent Volumes. These are powerful concepts that will help you build more resilient and scalable applications.
