### ISSUE TITLE
challenge-running-pod-with-daemonsets

### ISSUE THREAD

**Issue by joker-bai** [labex-labs/scenarios#703]
> **Please read [For Newbie](https://github.com/labex-labs/scenarios/issues/18) first. 请先阅读 [新手须知](https://github.com/labex-labs/scenarios/issues/18)。**

## Basic

> Basic information about the scenario, which can be changed if required.
> 实验/挑战的基本信息，如有需要，可以修改。

- **Suggest Title 建议标题**: Running Pod With DaemonSets
- **Suggest Steps 建议步骤数**: 5
- **Suggest Image 建议环境**: `webide-instance-ubuntu:2204`

## Sources

> Issues has provided the material; the part not provided must be completed by the author.
> Issues 已经提供了材料；没有提供的部分由作者自行补充完成。

- [x] Full Text 正文内容
- [x] Reference Answers 参考答案
- [ ] Verify Script 检测脚本

## Skills

> Suggested skills to include can be modified as needed. **The main skill points that should be included in this section are bolded**. From [Skills Tree (Click to apply for permission after logging in)](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp).
> 建议包括的 Skills ID，可以根据需要增删。**本章节应包含的主要技能点已加粗**，技能点来自 [技能树 (登录后点击申请权限)](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp)

- **`kubernetes/apply`**
- `kubernetes/get`

**Comment by joker-bai** [comment]
# Running Pod With DaemonSets

## Introduction

In Kubernetes, a DaemonSet is a type of controller that ensures a copy of a pod is running on every node in the cluster. This lab will guide you through the process of creating a DaemonSet to run replicas of a pod on every node in the cluster.

## Step 1: Create a Pod

### Introduction

In this lab, we will create a pod in kubernetes.

### Target

Your goal is to create a pod called `myapp-pod` in the kubernetes.

### Result Example

Here is an example of what you should be able to accomplish at the end of this step:

1. Create a file named `myapp-pod.yaml`, The content of the YAML is created as follows:

- The name of the pod called `myapp-pod`.
- The deployment's image is `nginx:latest`.
- Declare port `80` of the container.

2. Use `kubectl apply` command to deploy the YAML file.

### Solution

Create a simple pod that will be used as the template for the replicas. Create a file called `myapp-pod.yaml` with the following contents:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
spec:
  containers:
    - name: myapp-container
      image: nginx
      ports:
        - containerPort: 80
```

Create the pod using the following command:

```shell
kubectl apply -f myapp-pod.yaml
```

## Step 2: Create a DaemonSet

### Introduction

In this lab, we will learn how to create a daemonset in kubernetes.

### Target

Your goal is to create a daemonset named `myapp-daemonset` in the kubernetes. The daemonset will run the `nginx` image and will run only one instance. The image will be run on each node in the cluster.

### Result Example

Here is an example of what you should be able to accomplish at the end of this step:

1. Create a file named `myapp-daemonset.yaml`, The content of the YAML is created as follows:

- The name of the daemonset called `myapp-daemonset`.
- The deployment's image is `nginx:latest`.
- Declare port `80` of the container.

2. Use `kubectl apply` command to deploy the YAML file.

### Solution

Create a DaemonSet to run replicas of the `myapp-pod` on every node in the cluster. Create a file called `myapp-daemonset.yaml` with the following contents:

```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: myapp-daemonset
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp-container
          image: nginx
          ports:
            - containerPort: 80
```

This DaemonSet uses the `myapp-pod` as the template for the replicas and sets the `matchLabels` selector to `app: myapp` to ensure that the replicas are created on every node.

Create the DaemonSet using the following command:

```shell
kubectl apply -f myapp-daemonset.yaml
```

## Step 3: Verify the DaemonSet

### Introduction

Verifying a DaemonSet in Kubernetes involves ensuring that the desired number of pods are running on the target nodes, and that the pods are healthy and functioning as expected. In this lab, we will learn how to verify the daemonset has been created.

### Target

Your goal is to verify that the daemonset has been successfully created.

### Result Example

Here is an example of what you should be able to accomplish at the end of this step:

1. Use `kubectl get` command to list the pods created by daemonset.

### Solution

Verify that the DaemonSet has been created and that replicas of the `myapp-pod` are running on every node. Use the following command to list the nodes in the cluster:

```shell
kubectl get nodes
```

Use the following command to list the pods created by the DaemonSet:

```shell
kubectl get pods -l app=myapp
```

You should see one pod for each node in the cluster.

## Step 4: Update the DaemonSet

### Introduction

Updating a DaemonSet in Kubernetes involves modifying the DaemonSet specification to reflect the desired changes, and then rolling out the changes to the cluster. There are several different strategies that can be used to update a DaemonSet, depending on the specific requirements of the application. In this lab, we will update the image of the daemonset.

### Target

Your goal is to modify the image of the DaemonSet called `myapp-daemonset` to `busybox:latest` and add the `sleep 3600` start command to it.

### Result Example

Here is an example of what you should be able to accomplish at the end of this step:

1. Create a file named `myapp-daemonset-update.yaml`, The content of the YAML is created as follows:

- The name of the daemonset called `myapp-daemonset`.
- Update the deployment's image is `busybox:latest`.
- The command is `sleep 3600`.

2. Use `kubectl apply` command to deploy the YAML file.

### Solution

Update the DaemonSet to change the image used by the `myapp-container`. Create a file called `myapp-daemonset-update.yaml` with the following contents:

```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: myapp-daemonset
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp-container
          image: busybox
          command: ["sleep", "3600"]
```

This updated DaemonSet changes the image used by the `myapp-container` to `busybox` and sets the command to `sleep 3600`.

Update the DaemonSet using the following command:

```shell
kubectl apply -f myapp-daemonset-update.yaml
```

## Step 5: Verify the Update

### Introduction

In this lab, we will learn how to check that the Daemonset changes are in effect.

### Target

Your goal is to check that the image modified by the Daemonset named `myapp-daemonset` is `busybox:latest`.

### Result Example

Here is an example of what you should be able to accomplish at the end of this step:

1. Use `kubectl get` command to list the pods created by Daemonset.

### Solution

Verify that the DaemonSet has been updated and that replicas of the `myapp-pod` are running with the new image. Use the following command to list the pods created by the DaemonSet:

```shell
kubectl get pods -l app=myapp
```

You should see new pods created with the updated image.

## Summary

In this lab, you learned how to use a DaemonSet in Kubernetes to run replicas of a pod on every node in the cluster.
