### ISSUE TITLE
challenge-containerprobe-in-kubernetes

### ISSUE THREAD

**Issue by joker-bai** [labex-labs/scenarios#746]
> **Please read [For Newbie](https://github.com/labex-labs/scenarios/issues/18) first. 请先阅读 [新手须知](https://github.com/labex-labs/scenarios/issues/18)。**

## Basic

> Basic information about the scenario, which can be changed if required.
> 实验/挑战的基本信息，如有需要，可以修改。

- **Suggest Title 建议标题**: ContainerProbe in Kubernetes
- **Suggest Steps 建议步骤数**: 5
- **Suggest Image 建议环境**: `webide-instance-ubuntu:2204`

## Sources

> Issues has provided the material; the part not provided must be completed by the author.
> Issues 已经提供了材料；没有提供的部分由作者自行补充完成。

- [x] Full Text 正文内容
- [x] Reference Answers 参考答案
- [ ] Verify Script 检测脚本

## Skills

> Suggested skills to include can be modified as needed. **The main skill points that should be included in this section are bolded**. From [Skills Tree (Click to apply for permission after logging in)](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp).
> 建议包括的 Skills ID，可以根据需要增删。**本章节应包含的主要技能点已加粗**，技能点来自 [技能树 (登录后点击申请权限)](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp)

- **`kubernetes/apply`**
- `kubernetes/get`
- `kubernetes/describe`

**Comment by joker-bai** [comment]
# ContainerProbe in Kubernetes

## Introduction

In Kubernetes, a probe is a diagnostic tool used to determine whether a container is alive and ready to accept traffic. There are two types of probes, liveness probes and readiness probes. In this lab, we will focus on ContainerProbe, which is a tool used to detect when a container is ready to accept traffic.

## Step 1: Create a Deployment

### Introduction

In Kubernetes, a Deployment is a high-level controller that manages Pods, providing a simple way to create and update them. In this lab, we will learn how to create a Deployment.

### Target

Your goal is to create a Deployment called `containerprobe-deployment` with a replica count of `1` in Kubernetes using the `nginx:latest` image.

### Resule Example

Here is an example of what you should be able to accomplish at the end of this step:

1. Create a YAML file called `deployment.yaml` with `1` replicas, running an Nginx container.
2. Use `kubectl apply` command to create the `containerprobe-deployment` Deployment.

### Solution

The first step is to create a deployment in Kubernetes. We will use this deployment to test the ContainerProbe.

1. Create a new file named `deployment.yaml`.
2. Copy and paste the following code into the file:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: containerprobe-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: containerprobe
  template:
    metadata:
      labels:
        app: containerprobe
    spec:
      containers:
        - name: containerprobe
          image: nginx
          ports:
            - containerPort: 80
```

This code creates a deployment with one replica, a selector with the label `app: containerprobe`, and a container running the nginx image.

3. Apply the deployment to your cluster:

```bash
kubectl apply -f deployment.yaml
```

## Step 2: Add a Liveness Probe

### Introduction

A liveness probe is used to determine if the container is alive. If the probe fails, Kubernetes will restart the container. In this lab, we will learn how to add a liveness probe to the nginx container.

### Target

Your goal is to add liveness probe to the `nginx` container for the Deployment called `containerprobe-deployment`. The liveness probe should send an `HTTP GET` request to the `root path` on port `80`.

### Resule Example

Here is an example of what you should be able to accomplish at the end of this step:

1. Update the `deployment.yaml` file with the follows.

- Add the liveness probe.
- The probe use `httpGet` request.
- The address for the test is `/`.
- The port for the test is `80`.

2. Use `kubectl apply` command to update the deployment.

### Solution

The next step is to add a liveness probe to the nginx container. A liveness probe is used to determine if the container is alive. If the probe fails, Kubernetes will restart the container.

1. Update the `deployment.yaml` with the follow content:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: containerprobe-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: containerprobe
  template:
    metadata:
      labels:
        app: containerprobe
    spec:
      containers:
        - name: containerprobe
          image: nginx
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
```

This code specifies that the liveness probe should send an HTTP GET request to the root path on port 80.

2. Update the deployment:

```bash
kubectl apply -f deployment.yaml
```

## Step 3: Test the Liveness Probe

### Introduction

In this lab, we will learn how to test the liveness probe that we added.

### Target

Your goal is to use the `kubectl describe` command to test the liveness probe is working correctly.

### Resule Example

Here is an example of what you should be able to accomplish at the end of this step:

1. Get the pod name.
2. Use `kubectl describe` command to get the status of the liveness probe.

### Solution

Now that we have added a liveness probe, we can test it to see if it is working correctly.

1. Get the pod name:

```bash
kubectl get pods -l app=containerprobe -o jsonpath='{.items[0].metadata.name}'
```

This command gets the name of the pod created by the deployment.

2. Get the status of the liveness probe:

```bash
kubectl describe pod <pod-name>
```

Replace `<pod-name>` with the name of the pod from the previous step.

You should see output that includes the following:

```bash
Liveness: http-get http://:80/ delay=0s timeout=1s period=10s #success=1 #failure=3
```

This indicates that the liveness probe is configured correctly.

## Step 4: Add a Readiness Probe

### Introduction

A readiness probe is used to determine if the container is ready to accept traffic. If the probe fails, Kubernetes will not send traffic to the container. In this lab, we will learn how to add a readiness probe to the nginx container.

### Target

Your goal is to add readiness probe to the `nginx` container for the Deployment called `containerprobe-deployment`. The readiness probe should send an `HTTP GET` request to the `root path` on port `80`.

### Resule Example

Here is an example of what you should be able to accomplish at the end of this step:

1. Update the `deployment.yaml` file with the follows.

- Add the readiness probe.
- The probe use `httpGet` request.
- The address for the test is `/`.
- The port for the test is `80`.

2. Use `kubectl apply` command to update the deployment.

### Solution

The next step is to add a readiness probe to the nginx container. A readiness probe is used to determine if the container is ready to accept traffic. If the probe fails, Kubernetes will not send traffic to the container.

1. Add the following code to the container definition in `deployment.yaml`

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: containerprobe-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: containerprobe
  template:
    metadata:
      labels:
        app: containerprobe
    spec:
      containers:
        - name: containerprobe
          image: nginx
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
```

This code specifies that the readiness probe should send an HTTP GET request to the root path on port 80.

2. Update the deployment:

```bash
kubectl apply -f deployment.yaml
```

## Step 5: Test the Readiness Probe

### Introduction

In this lab, we will learn how to test the readiness probe that we added.

### Target

Your goal is to use the `kubectl describe` command to test the readiness probe is working correctly.

### Resule Example

Here is an example of what you should be able to accomplish at the end of this step:

1. Get the pod name.
2. Use `kubectl describe` command to get the status of the readiness probe.

### Solution

Now that we have added a readiness probe, we can test it to see if it is working correctly.

1. Get the pod name:

```bash
kubectl get pods -l app=containerprobe -o jsonpath='{.items[0].metadata.name}'
```

This command gets the name of the pod created by the deployment.

2. Get the status of the readiness probe:

```bash
kubectl describe pod <pod-name>
```

Replace `<pod-name>` with the name of the pod from the previous step.

You should see output that includes the following:

```bash
Readiness: http-get http://:80/ delay=0s timeout=1s period=10s #success=1 #failure=3
```

This indicates that the readiness probe is configured correctly.

## Summary

In this lab, we learned how to use ContainerProbe in Kubernetes. We created a deployment, added a liveness probe, tested the liveness probe, added a readiness probe, and tested the readiness probe. By using ContainerProbe, we can ensure that our containers are ready to accept traffic and are functioning correctly.
