### ISSUE TITLE
challenge-using-horizontalpodautoscaler-in-kubernetes

### ISSUE THREAD

**Issue by joker-bai** [labex-labs/scenarios#748]
> **Please read [For Newbie](https://github.com/labex-labs/scenarios/issues/18) first. 请先阅读 [新手须知](https://github.com/labex-labs/scenarios/issues/18)。**

## Basic

> Basic information about the scenario, which can be changed if required.
> 实验/挑战的基本信息，如有需要，可以修改。

- **Suggest Title 建议标题**: Using HorizontalPodAutoscaler in Kubernetes
- **Suggest Steps 建议步骤数**: 3
- **Suggest Image 建议环境**: `webide-instance-ubuntu:2204`

## Sources

> Issues has provided the material; the part not provided must be completed by the author.
> Issues 已经提供了材料；没有提供的部分由作者自行补充完成。

- [x] Full Text 正文内容
- [x] Reference Answers 参考答案
- [ ] Verify Script 检测脚本

## Skills

> Suggested skills to include can be modified as needed. **The main skill points that should be included in this section are bolded**. From [Skills Tree (Click to apply for permission after logging in)](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp).
> 建议包括的 Skills ID，可以根据需要增删。**本章节应包含的主要技能点已加粗**，技能点来自 [技能树 (登录后点击申请权限)](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp)

- **`kubernetes/apply`**
- `kubernetes/get`
- `kubernetes/run`

**Comment by joker-bai** [comment]
# Using HorizontalPodAutoscaler in Kubernetes

## Introduction

HorizontalPodAutoscaler is a Kubernetes feature that allows you to automatically scale the number of pods in a deployment based on resource utilization. In this lab, we will learn how to use HorizontalPodAutoscaler to automatically scale our deployment.

## Step 1: Create a Deployment

### Introduction

In Kubernetes, a Deployment is a high-level controller that manages Pods, providing a simple way to create and update them. In this lab, we will learn how to create a Deployment.

### Target

Your goal is to create a Deployment called `hpa-demo` with a replica count of `1` in Kubernetes using the `nginx:latest` image. And configurations for resource requests and resource limits will also be set for Pods.

### Result Example

Here is an example of what you should be able to accomplish at the end of this step:

1. Create a YAML file called `deployment.yaml` with the follows.

- The name is `hpa-demo`.
- The replicas of the deployment is `1`.
- The image of the deployment is `nginx`.
- The CPU resource request configuration is `0.5` and memory is `256Mi`.
- The CPU resource limit configuration is `1` and memory is `512Mi`.
- Create a Service named `hpa-demo` which sees a Deployment named `hpa-demo` selected by the `app: hpa-demo` selector.

2. Use `kubectl apply` command to create the `hpa-demo` Deployment.

### Solution

First, we need to create a deployment to which we will apply the HorizontalPodAutoscaler.

1. Create a deployment file named `deployment.yaml` with the following contents:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpa-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hpa-demo
  template:
    metadata:
      labels:
        app: hpa-demo
    spec:
      containers:
        - name: hpa-demo
          image: nginx
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
            requests:
              cpu: "0.5"
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: hpa-demo
spec:
  selector:
    app: hpa-demo
  ports:
    - name: http
      port: 80
      targetPort: 80
```

This deployment specifies a single replica of an Nginx container with resource limits and requests for CPU and memory.

2. Create the deployment:

```bash
kubectl apply -f deployment.yaml
```

## Step 2: Create a HorizontalPodAutoscaler

### Introduction

In this lab, we will learn how to create a HorizontalPodAutoscaler to automatically scale the deployment.

### Target

Your goal is to create a HorizontalPodAutoscaler specifies called `hpa-demo`, that it will to scale the `hpa-demo` deployment to have between `1` and `10` replicas, and that we want to target an average CPU utilization of `1%`.

### Result Example

Here is an example of what you should be able to accomplish at the end of this step:

1. Create a HorizontalPodAutoscaler file named `hpa.yaml` with the follow

- The name is `hpa-demo`.
- It will to scale the `hpa-demo` deployment to have between `1` and `10` replicas.
- Add the target an average CPU utilization of `1%`.

2. Use `kubectl apply` command to create it.

### Solution

Now that we have a deployment, we can create a HorizontalPodAutoscaler to automatically scale the deployment.

1. Create a HorizontalPodAutoscaler file named `hpa.yaml` with the following contents:

```yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-demo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hpa-demo
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          averageUtilization: 1
          type: Utilization
```

This HorizontalPodAutoscaler specifies that we want to scale the `hpa-demo` deployment to have between 1 and 10 replicas, and that we want to target an average CPU utilization of 1%.

2. Create the HorizontalPodAutoscaler:

```bash
kubectl apply -f hpa.yaml
```

## Step 3: Test the HorizontalPodAutoscaler

### Introduction

In this lab, we will leatn how the the HorizontalPodAutoscaler by generating load on the deployment.

### Target

Your goal is to test if the corresponding HorizontalPodAutoscaler works by adding load to the deployment named `hpa-demo`.

### Result Example

Here is an example of what you should be able to accomplish at the end of this step:

1. Use `minikube addons` commandd to enable the `metrice-server`.
2. Use the `busybox` image to create a load generation pod.
3. Use `wget` command to accesses the destination URL `http://hpa-demo` in an infinite loop.
4. Open another terminal, check the status of the HorizontalPodAutoscaler.
5. Check the number of replicats (number of nodes) the Deployment.
6. Stop the load generation by typing `ctrl+c` in the load generation pod.

### Solution

Now that we have a HorizontalPodAutoscaler, we can test it by generating load on the deployment.

1. Enable the metrice-server

```bash
minikube addons enable metrics-server
```

2. Create a load generation pod:

```bash
kubectl run -i --tty load-generator --image=busybox /bin/sh
```

3. In the load generation pod, run the following command to generate load on the deployment:

```bash
while true; do wget -q -O- http://hpa-demo; done
```

4. Open another terminal, check the status of the HorizontalPodAutoscaler:

```bash
kubectl get hpa
```

You can see that the number of copies of `hpa-demo` has been extended to `10`. You can check the number of replicas with the following command.

```bash
kubectl get pods -l app=hpa-demo
```

5. Stop the load generation by typing `ctrl+c` in the load generation pod.

## Summary

In this lab, we learned how to use HorizontalPodAutoscaler to automatically scale a deployment based on resource utilization. We created a deployment, created a HorizontalPodAutoscaler, and tested it by generating load on the deployment. We also saw how the HorizontalPodAutoscaler scaled the deployment in response to the increased load.
