### ISSUE TITLE
challenge-kubernetes-service-account

### ISSUE THREAD

**Issue by GuoJiang-yw** [labex-labs/scenarios#820]
> **Please read [For Newbie](https://github.com/labex-labs/scenarios/issues/18) first. 请先阅读 [新手须知](https://github.com/labex-labs/scenarios/issues/18)。**

## Basic

> Basic information about the scenario, which can be changed if required.
> 实验/挑战的基本信息，如有需要，可以修改。

- **Suggest Title 建议标题**: Kubernetes Service Account
- **Suggest Steps 建议步骤数**: 3
- **Suggest Image 建议环境**: `webide-instance-ubuntu:2204`

## Sources

> Issues has provided the material; the part not provided must be completed by the author.
> Issues 已经提供了材料；没有提供的部分由作者自行补充完成。

- [ ] Full Text 正文内容
- [ ] Reference Answers 参考答案
- [ ] Verify Script 检测脚本

## Skills

> Suggested skills to include can be modified as needed. **The main skill points that should be included in this section are bolded**. From [Skills Tree (Click to apply for permission after logging in)](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp).
> 建议包括的 Skills ID，可以根据需要增删。**本章节应包含的主要技能点已加粗**，技能点来自 [技能树 (登录后点击申请权限)](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp)

- **`kubernetes/apply`**
- `kubernetes/create`
- `kubernetes/describe`

**Comment by GuoJiang-yw** [comment]
# Kubernetes Service Account

## Introduction

Kubernetes Service Account is a mechanism for authenticating with the Kubernetes API server. In this challenge, we will start with simple examples and move towards more complex ones to help you learn about Service Account in Kubernetes. Each step will have an Introduction, Target, Result Example, Solution, and Requirements. 

## Step 1: Creating a Service Account

### Introduction

In this step, you will learn how to create a Service Account using kubectl command and YAML file.

### Target

Create a Service Account in Kubernetes.

### Result Example

Here is an example of what you should be able to accomplish at the end of this challenge:

- A Service Account named `my-service-account` is created.

### Solution

Run the following command to create a Service Account:

```bash
kubectl create sa my-service-account
```

## Step 2: Creating a Role and RoleBinding

### Introduction

In this step, you will learn how to create a Role and RoleBinding to grant permissions to a Service Account.

### Target

Create a Role and RoleBinding to grant permissions to a Service Account.

### Result Example

Here is an example of what you should be able to accomplish at the end of this challenge:

- Create a YAML file named `role.yaml` to defining a Role named `my-role` with rules that allow the `get` and `list` verbs for the pods resource in the empty apiGroups.
- A RoleBinding named `my-role-binding` is created to bind the Role to the Service Account `my-service-account`.

### Solution

1. Create a YAML file named `role.yaml` with the following content:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: my-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
```

2. Run the following command to create the Role:

```bash
kubectl apply -f role.yaml
```

3. Create a YAML file named `rolebinding.yaml` with the following content:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: my-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: my-role
subjects:
- kind: ServiceAccount
  name: my-service-account
  namespace: default
```

4. Run the following command to create the RoleBinding:

```bash
kubectl apply -f rolebinding.yaml
```

## Step 3: Using Service Account in a Pod

### Introduction

In this step, you will learn how to use a Service Account in a Pod to access the Kubernetes API server.

### Target

Create a Pod that uses the Service Account to access the Kubernetes API server.

### Result Example

Here is an example of what you should be able to accomplish at the end of this challenge:
- A Pod named `my-pod` is created that uses the Service Account `my-service-account` to access the Kubernetes API server.

### Solution

1. Create a YAML file named `pod.yaml` with the following content:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: my-container
    image: busybox
    command: ['sh', '-c', 'while true; do sleep 3600; done']
    env:
    - name: MY_POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
  serviceAccountName: my-service-account
```

2. Run the following command to create the Pod:

```bash
kubectl apply -f pod.yaml
```

## Conclusion

In this challenge, you learned about Kubernetes Service Account and how to create a Service Account, create a Role and RoleBinding, and use a Service Account in a Pod to access the Kubernetes API server. These are the fundamental concepts of Service Account in Kubernetes, and you can build upon these concepts to achieve more complex tasks.
